settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.mybitti.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: hub-page # unique identifier
    name: hub.tenno.dev
    description: 'hub.tenno.dev' # default=empty
    url: 'https://hub.tenno.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api-tenno
    name: api3.tenno.dev
    description: 'api3.tenno.dev'
    url: 'https://api3.tenno.dev'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
